

module.exports = {

    UI: {
        UPLOADING_IMAGES: 'UPLOADING_IMAGES',
        UPLOADING_IMAGES_COMPLETE: 'UPLOADING_IMAGES_COMPLETE',
        FETCHING_IMAGES: 'FETCHING_IMAGES',
        FETCHING_IMAGES_COMPLETE: 'FETCHING_IMAGES_COMPLETE'
    },

    GALLERY: {
        SET_GALLERY: 'SET_GALLERY'
    }

};
